require 'rspec/models/unidom/action/reason_spec'           unless Unidom::Common::Neglection.namespace_neglected? 'Unidom::Action::Reason'
require 'rspec/models/unidom/action/acting_spec'           unless Unidom::Common::Neglection.namespace_neglected? 'Unidom::Action::Acting'
require 'rspec/models/unidom/action/state_transition_spec' unless Unidom::Common::Neglection.namespace_neglected? 'Unidom::Action::StateTransition'
require 'rspec/models/unidom/action/obsolescing_spec'      unless Unidom::Common::Neglection.namespace_neglected? 'Unidom::Action::Obsolescing'
require 'rspec/models/unidom/action/searching_spec'        unless Unidom::Common::Neglection.namespace_neglected? 'Unidom::Action::Searching'
