require 'rspec/models/unidom/action/concerns/as_acted_shared_examples'
require 'rspec/models/unidom/action/concerns/as_actor_party_shared_examples'
require 'rspec/models/unidom/action/concerns/as_caused_shared_examples'
require 'rspec/models/unidom/action/concerns/as_obsolesced_shared_examples'
require 'rspec/models/unidom/action/concerns/as_obsolescer_party_shared_examples'
require 'rspec/models/unidom/action/concerns/as_searcher_party_shared_examples'
require 'rspec/models/unidom/action/concerns/as_state_subject_shared_examples'
